version: "3"

services: 
  web:
    image: muqimjon/info
    container_name: info
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    networks:
      - dev

  db:
    image: postgres:11.1
    ports:
      - "5050:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USERNAME: postgres
    networks:
      - dev

networks:
  dev:
    driver: bridge