# setup
name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# dockerize
jobs:
  dockerize:
    name: Dockerize
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      REPOSITORY: ${{ secrets.DOCKER_REPOSITORY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
      - name: Build Docker image
        run: docker build -t $USERNAME/$REPOSITORY -f .\src\InfoZest.WebApi\Dockerfile .
      - name: Login to Docker account
        run: docker login -u $USERNAME -p $PASSWORD #--password-stdin
      - name: Push Docker image
        run: docker push $USERNAME/$REPOSITORY
